import { from } from 'rxjs';

export * from './dashboard/dashboard.component';
export * from './profile/profile-update.component';
export * from './grades/grade.component';
export * from './webinar/create/create.component';
export * from './webinar/list/list.component';
export * from './webinar/update/update.component';
export * from './my-schedule/list/list.component';
export * from './my-schedule/detail/detail.component';
export * from './schedule/schedule.component';
export * from './my-lesson/list/list.component';
export * from './my-lesson/detail/detail.component';
export * from './favorite/favorite.component';
export * from './course/create/create.component';
export * from './course/list/list.component';
export * from './course/update/update.component';
export * from './course/course-coupon/course-coupon.component';
export * from './course/course-goal/course-goal.component';
export * from './course/course-lecture/course-lecture.component';
export * from './course/modal-section/section-form';
export * from './course/modal-lecture/lecture-form';
export * from './my-course/list/list.component';
export * from './my-course/detail/detail.component';
export * from './course-transaction/list/list.component';
export * from './course-transaction/detail/detail.component';
// export * from './profile/modal-mysubject/my-subject';
export * from './my-category';
export * from './modal-appointment/modal-appointment.component';
